name: possystem
description: POS system by Flutter
publish_to: "none"
homepage: https://github.com/evan361425/flutter-pos-system
version: 2.10.2+21002003

environment:
  flutter: ">=3.24.0 <3.25.0"
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core helper
  go_router: ^14.3.0
  # git:
  #   url: https://github.com/evan361425/flutter-packages
  #   path: packages/go_router
  #   ref: main
  provider: ^6.1.2
  intl: ^0.19.0
  collection: ^1.18.0
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  firebase_crashlytics: ^3.5.7
  firebase_in_app_messaging: ^0.7.5+7

  # services
  sqflite: ^2.4.0  # 24, 10-07
  sembast: ^3.7.5  # 24, 10-05
  shared_preferences: ^2.3.2
  http: ^1.2.2
  bluetooth:
    git:
      url: https://github.com/evan361425/flutter-pos-packages
      ref: master
      path: packages/bluetooth
  flutter_blue_plus:
    git:
      url: https://github.com/evan361425/flutter_blue_plus
      ref: uint8

  # google services
  googleapis: ^13.2.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12

  # components
  table_calendar: ^3.1.2  # 24, 06-09
  syncfusion_flutter_charts: ^27.1.54
  spotlight_ant: ^1.4.3

  # image
  image: ^4.3.0  # 24, 10-15
  image_picker: ^1.1.2  # 24, 05-31
  image_cropper: ^8.0.2  # 24, 08-16
  cached_network_image: ^3.4.0  # 24, 08-13, downgrade for firebase
  flutter_svg: ^2.0.11  # 24, 10-31

  # Make it easy to test
  file: ^7.0.1  # 24, 10-08

  # tools
  uuid: ^4.5.1  # 24, 09-26
  wakelock:
    git:
      url: https://github.com/evan361425/wakelock
      path: wakelock/
      ref: main
  characters: ^1.3.0  # 24, 10-16
  path_provider: ^2.1.5  # 24, 10-29
  url_launcher: ^6.3.1  # 24, 10-08
  flutter_native_splash: ^2.4.2  # 24, 10-20
  package_info_plus: ^8.1.0  # 24, 10-17
  visibility_detector: ^0.4.0+2  # 23, 03-09
  cupertino_icons: ^1.0.8  # This is for google-package which use it in some case

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code style
  flutter_lints: ^5.0.0

  # mock object
  build_runner: ^2.4.13
  mockito: ^5.4.4
  sqflite_common: ^2.5.4+5  # logging
  sqflite_common_ffi: ^2.3.4

  arb_glue: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
  - assets/food_placeholder.png
  - assets/google_sheet_icon.svg
  - assets/feature_request_please.gif
  - assets/google_signin_button.svg

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#5c98ff"
  fullscreen: true
  image: assets/logo.png

arb_glue:
  source: assets/l10n
  destination: lib/l10n
  author: Lu Shueh Chou
  fileTemplate: 'app_{lang}.arb'
  base: en
  verbose: true
